[project]
name = "impure-package"
version = "0.1.0"
description = "Add your description here"
authors = [ ]
requires-python = ">=3.13"
dependencies = [
    "dash>=3.4.0",
    "dash-mantine-components>=2.5.1",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]
